### PR TITLE
Feature/UI livechat

### PR DESCRIPTION
**Pull request by TheblueMan003**
# What?
## Chat UI
Adds a button in meetup view to access the chat
User can currently view message from the chat and send message
Clicking on a profil picture from the chat send to the profile page

## Navigation Bar
A fragment that can be added to any Activity. No Need to add code for it in the activity
Present on the following activities: Main, Map, MeetupList

### CODE REVIEW

**Comment by TruddyTheDuddi** [comment]
I've mostly checked the UI itself inside your branch for the chat, for a basic design it looks good, however will need to be changed to match the color scheme, fixing some padding for the message boxes. 

Also the "click image to access profile" seems to be missing for now.

**Bug:** Time on the messages should be updated every once in a while, because they stay the same until they exit the recycle view by scrolling. Maybe a normal time such as "14:40" should be used here, it could be integrated more easily

But overall looking good so far! Good job

**Comment by zaclegarssure** [comment]
Overall pretty good, one thing is that when you are in a chat and you deploy the keyboard, this should push the message upward I thing, to let you still see the last message(s).

**Comment by zaclegarssure** [comment]
Also there seems to be a problem, only pal finder (the account) is fetched correctly if I use another account it failes.

**Comment by TruddyTheDuddi** [comment]
@zaclegarssure Does it not display the profile when you are the one posting? I need to re-check then
Also @TheblueMan003 do you plant to augment the code coverage of some files with test this week or will you do it next week?

**Review by atappy — APPROVED** [review]
seems good, I just think we're gonna need to change the UI at some point

**Review by TruddyTheDuddi — APPROVED** [review]

**Pull request merged**
