### PR TITLE
User/settings

### PR DESCRIPTION
**Pull request by TruddyTheDuddi**
Created the basic structure for the user settings with appropriate and responsive UI design.

**Files**
`activity_user_settings.xml` and `UserSettingsActivity.kt`

### CODE REVIEW

**Comment by zaclegarssure** [comment]
The ui is really nice, only problem is that the name and surname (and also username I guess) accepts multi line strings, which is probably not what we want.

**Comment by TruddyTheDuddi** [comment]
@zaclegarssure good point, thanks for reporting!

**Review by atappy — APPROVED** [review]
good job, all seem all right

**Review by TheblueMan003 — APPROVED** [review]
Looks good to me. (Also nice UI 👍)

**Pull request merged**
