### PR TITLE
Feature/main navigation

### PR DESCRIPTION
**Pull request by zaclegarssure**
## What?
Transformed the map, list and meetup creation into fragments and hook them together using the navigation component.

## Details
This tries to convert the main flow of the app, previously composed by the map, list and creation activities, into a single activity, `mainNavActivity.kt` which posses a fragment container in which the different views (which are now fragments) flow.
This uses the [jetpack navigation component](https://developer.android.com/guide/navigation), and [safe args](https://developer.android.com/guide/navigation/navigation-pass-data). The idea is that you define a graph describing how your app navigates between fragments (and also activities) and each fragment posses a navigationController to easily walk along this graph. You can easily specify which argument should be passed between destinations, with type safety, using safeArgs. The mainActivity only focus on certain global navigation part (such as the navBar) while fragment only focus on themself and navigating is simply a function call to the navigationController.
This make it easy to have a coherent flow (actually it wasn't lel) and to add custom animation to different transition. Since things are fragments, we can do all sort of very fancy stuff, which we will do later I guess. For now I just used translations.
Also note that here we have to navigation graph, because the find section of the app contains a map and a list representation, which formed a sub-graph and since this is kind of weird I had to implement things in a slightly awkward way for the `findFragment.kt`.
Here are the important files:
- `navigation/MainNavActivity.kt` This is the main activity with the fragment container (called a navHostFragment). It also include the logic that drives the navBar, which is now embedded in the activity rather than being a separate fragment.
- `navigation/FindFragment.kt` This is the fragment containing the two tabs, map and list, which handle it's own local navigation, with again a navHostFragment.
- `navigation/FindViewModel.kt` This simply stores which tab was open in the find fragment, to make the navigation a bit more consistent.
- `map/MapsFragment.kt` This file is the MapActivity but converted in a fragment, for some reason android studio while renaming didn't perform a git rename which now make it seem that I deleted the MapActivity, which will make merging hard I guess, cool... This fragment contains also features related to the map which were before in the viewModel this however created a memory leak so that's why I had to move things in the fragment.
- The mapSelectionViewModel was also deleted for the same memory leak reason.
- `meetup/activities/*` The viewModel is now shared between the map and the list, some location stuff are handled here but this does not really work. The list fragment is a little more flexible. The superMapList was removed, and the common features were merged in the viewModel, since it is shared now. MeetUpCreation is now a fragment too. bla bla bla.
- 

## Tests
Tests were adapted and added to test the navigation, the overall coverage improve a bit and the diff coverage is clearly good.

## Known issues
The navigation should be extended to the other part of the app I think, to make everything consistent.
Also some feature related to the map (zoom level and user location) are only partially reworked, but that will be done in another PR.
Transition are a little bit "cheap", those are simple translation for now but you already notice some slowdown when transitioning to the meetup list fragment, I will do a bit of profiling to see what's taking so much resource in there., but that's probably something that was already here before. Okay actually that might be an issue with transition to recyclerView in general.

### CODE REVIEW

**Review by atappy — COMMENTED** [review]
very good job, just make sure to delete the navbar from the mainNavActivity (it leads to nothing and makes the app crash currently.
Also could you add a way to access the meetupcreation ? Or is it already done and I just missed it ?

**Comment by zaclegarssure** [comment]
> 

The nav bar is already deleted from the main nav activity, this is the new one that you were probably using that let you access all the three main features (create, find and groups) so if it crashes that mean something weird is going on, can you make sure you were on the right activity ? I will try on my side.

**Review by pgilliar — COMMENTED** [review]
The settings have no button to go back, are you gonna change this in this pr or in another ? And the button to edit profile does nothing

**Comment by zaclegarssure** [comment]
Edit profile never did anything, it was just for demonstration purpose (It should be there in some PR tho, but not mine I guess), for the back buttons to avoid changing everything we should put this at the last time of the sprint I guess.

**Comment by zaclegarssure** [comment]
I will merge it after the other PR if it is okay for you (to make as less conflict as possible).

**Review by pgilliar — APPROVED** [review]
Seems good

**Review by atappy — APPROVED** [review]

**Pull request merged**
